version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: EST
  open-pull-requests-limit: 10
  reviewers:
  - ssmirr
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: mustache
    versions:
    - 4.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
